global_costmap:
  update_frequency: 0.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 30
  height: 30
  origin_x: -7.5
  origin_y: -7.5
  static_map: true
  rolling_window: false 
  inflation_radius: 2.5
  resolution: 0.01
